---
server:
   port: 8089
   contextPath: /entity-test
---
hibernate:
    show_sql: true
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region:
            factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'
    environments:
        development:
            show_sql: true
        test:
            show_sql: true
        ci:
            show_sql: true
---
dataSource:
    dbCreate: none
    pooled: true
    driverClassName: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    username: enterUsername
    password: enterPassword
    url: jdbc:mysql://127.0.0.1:3306/entity_test?useUnicode=true
    properties :
        initialSize : 5
        maxActive : 50
        minIdle : 5
        maxIdle : 25
        maxWait : 600000
        maxAge : 600000
        timeBetweenEvictionRunsMillis : 300000
        minEvictableIdleTimeMillis : 300000
        validationQuery : "SELECT 1"
        validationQueryTimeout : 3
        validationInterval : 15000
        testOnBorrow : true
        testWhileIdle : true
        testOnReturn : false
        jdbcInterceptors : ConnectionState
        defaultTransactionIsolation : 2
---
grails:
   profile: web
   codegen:
       defaultPackage: entity.test
   spring:
       transactionManagement:
           proxies: false
   gorm:
       reactor:
           # Whether to translate GORM events into Reactor events
           # Disabled by default for performance reasons
           events: false
---
grails:
   mime:
       disable:
           accept:
               header:
                   userAgents:
                       - Gecko
                       - WebKit
                       - Presto
                       - Trident
       types:
           all: '*/*'
           atom: application/atom+xml
           css: text/css
           csv: text/csv
           form: application/x-www-form-urlencoded
           html:
             - text/html
             - application/xhtml+xml
           js: text/javascript
           json:
             - application/json
             - text/json
           multipartForm: multipart/form-data
           pdf: application/pdf
           rss: application/rss+xml
           text: text/plain
           hal:
             - application/hal+json
             - application/hal+xml
           xml:
             - text/xml
             - application/xmla
   urlmapping:
       cache:
           maxsize: 1000
   controllers:
       defaultScope: singleton
   converters:
       encoding: UTF-8
   views:
       default:
           codec: html
       gsp:
           encoding: UTF-8
           htmlcodec: xml
           codecs:
               expression: html
               scriptlets: html
               taglib: none
               staticparts: none
---
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
---
spring:
    groovy:
        template:
            check-template-location: false
---
# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true
        unique-names: true
---